[build]
  base = "/"
  publish = "."
  command = "#"

[build.environment]
  NODE_VERSION = "14"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.processing]
  skip_processing = false 